package tests1.tests;// Generated by Selenium IDE


import org.junit.Assert;
import org.junit.Test;
import tests1.models.Account;
import tests1.models.Mail;
import tests1.models.Page;
import tests1.models.SuperMail;


public class Tests extends TestBase {

    @Test
    public void sendMailToDrafts() {
        Page page = Page.builder().url("https://m.mail.ru/login").height(1920).width(1080).build();
        applicationManager.getPageHelper().openPage(page);
        Account account = Account.builder().domain("bk.ru").login("si1x").password("Simon000!").build();
        applicationManager.getLoginHelper().login(account);
        applicationManager.getClickerHelper().openMenu();
        applicationManager.getClickerHelper().clickOnNewMailButton();
        Mail mail = Mail.builder().receiver("si1x@bk.ru").text("!!!qwqwerqweewwerqwerqwrqwerweqrqwerqwerqwerwqerqwerwerqwerqwerqwerqwerqwereqwrerqwet\\n\\n-- \\nСемён К\\n").build();
        applicationManager.getMailCreationHelper().createNewMail(mail);
        applicationManager.getClickerHelper().clickSaveButton();
        applicationManager.getClickerHelper().clickOnDraftsByLinkAfterSaving();
        applicationManager.getClickerHelper().clickOnFirstRow();
        Mail mailData = applicationManager.getMailCreationHelper().getCreatedMailData();
        //в черновике должны совпадать и получатель и текст
        Assert.assertEquals(mail, mailData);
    }

    @Test
    public void sendFullMailWithCopyToMe() {
        Page page = Page.builder().url("https://m.mail.ru/login").height(1920).width(1080).build();
        applicationManager.getPageHelper().openPage(page);
        Account account = Account.builder().domain("bk.ru").login("si1x").password("Simon000!").build();
        applicationManager.getLoginHelper().login(account);
        applicationManager.getClickerHelper().openMenuByClickingOnIcon();
        applicationManager.getClickerHelper().clickOnNotes();
        applicationManager.getClickerHelper().clickOnCreateNewNoteIcon();
        SuperMail mailExtended = new SuperMail("si1x@bk.ru", "Супер текст Добавим ещё немного Ну всё хватит",
                "si1x@bk.ru", "Очень интересная тема");
        applicationManager.getMailCreationHelper().fillTheMailWithParameters(mailExtended);
        applicationManager.getClickerHelper().clickOnSendButton();
        applicationManager.getPageHelper().refreshPage();
        applicationManager.getClickerHelper().clickOnFirstRow();
        SuperMail mailExtendedData = applicationManager.getMailCreationHelper().getExtendedMailData();
        //необходимо проверить совпадение текста и темы письма, письмо приходит нам
        // (не нужно заходить с другого аккаунта и проверять получателя)
        Assert.assertEquals(mailExtended.getSubject(), mailExtendedData.getSubject());
        Assert.assertEquals(mailExtended.getText(), mailExtendedData.getText());
    }

    @Test
    public void deleteFirstIncomingMessage(){
        Page page = Page.builder().url("https://m.mail.ru/login").height(1920).width(1080).build();
        applicationManager.getPageHelper().openPage(page);
        Account account = Account.builder().domain("bk.ru").login("si1x").password("Simon000!").build();
        applicationManager.getLoginHelper().login(account);
        applicationManager.getClickerHelper().clickOnFirstRow();
        //забираем данные письма которое мы собираемся удалить
        SuperMail firstMailData = applicationManager.getMailCreationHelper().getExtendedMailData();
        applicationManager.getClickerHelper().deleteCurrentMessage();
        applicationManager.getClickerHelper().clickOnFirstRow();
        //забираем данные письма которое теперь лежит первым в списке
        SuperMail secondMailData = applicationManager.getMailCreationHelper().getExtendedMailData();
        //проверяем что данные писем не совпадают
        Assert.assertNotEquals(firstMailData, secondMailData);
    }

}
