package tests.tests;// Generated by Selenium IDE


import org.junit.Test;
import tests.models.Account;
import tests.models.Mail;
import tests.models.Page;
import tests.models.SuperMail;


public class TestSimpleSave extends TestBase {

    @Test
    public void sendMailToDrafts() {
        Page page = Page.builder().url("https://m.mail.ru/login").height(1920).width(1080).build();
        applicationManager.getPageHelper().openPage(page);
        Account account = Account.builder().domain("bk.ru").login("si1x").password("Simon000!").build();
        applicationManager.getLoginHelper().login(account);
        applicationManager.getClickerHelper().openMenu();
        applicationManager.getClickerHelper().clickOnNewMailButton();
        Mail mail = Mail.builder().receiver("si1x@bk.ru").text("qwerqwet\\n\\n-- \\nСемён К\\n").build();
        applicationManager.getMailCreationHelper().createNewMail(mail);
        applicationManager.getClickerHelper().clickSaveButton();
    }

    @Test
    public void sendFullMailWithCopyToMe() {
        Page page = Page.builder().url("https://m.mail.ru/login").height(1920).width(1080).build();
        applicationManager.getPageHelper().openPage(page);
        Account account = Account.builder().domain("bk.ru").login("si1x").password("Simon000!").build();
        applicationManager.getLoginHelper().login(account);
        applicationManager.getClickerHelper().openMenuByClickingOnIcon();
        applicationManager.getClickerHelper().clickOnNotes();
        applicationManager.getClickerHelper().clickOnCreateNewNoteIcon();
        SuperMail mailExtended = new SuperMail("si1x@bk.ru", "Супер текст Добавим ещё немного Ну всё хватит",
                "si1x@bk.ru", "Очень интересная тема");
        applicationManager.getMailCreationHelper().fillTheMailWithParameters(mailExtended);
        applicationManager.getClickerHelper().clickOnSendButton();
    }

}
